//! Registration of the `praxis_*` runtime symbols the JIT'd code calls (§10.2).
//!
//! The Cranelift JIT resolves imported symbols by name through a resolver
//! closure; this module hands it `(name -> function pointer)` pairs for every
//! `praxis_*` extern wrapper in `praxis-runtime::abi`. Each entry is looked up
//! by the exact symbol name the lowering emits.

use praxis_runtime::abi::*;
use praxis_runtime::shadow_frame::{praxis_pop_shadow_frame, praxis_push_shadow_frame};

/// Look up a `praxis_*` runtime symbol by name, returning its address as a
/// `*const u8`. Returns `None` for unknown names (Cranelift then reports the
/// unresolved import as a definition error — surfaced as a [`crate::JitError`]).
#[must_use]
pub fn resolve(name: &str) -> Option<*const u8> {
    let ptr: *const () = match name {
        "praxis_alloc_int" => praxis_alloc_int as *const (),
        "praxis_alloc_bool" => praxis_alloc_bool as *const (),
        "praxis_alloc_unit" => praxis_alloc_unit as *const (),
        "praxis_alloc_text" => praxis_alloc_text as *const (),
        "praxis_alloc_char" => praxis_alloc_char as *const (),
        "praxis_int_load" => praxis_int_load as *const (),
        "praxis_bool_load" => praxis_bool_load as *const (),
        "praxis_char_load" => praxis_char_load as *const (),
        "praxis_int_add" => praxis_int_add as *const (),
        "praxis_int_sub" => praxis_int_sub as *const (),
        "praxis_int_mul" => praxis_int_mul as *const (),
        "praxis_int_div" => praxis_int_div as *const (),
        "praxis_int_rem" => praxis_int_rem as *const (),
        "praxis_int_neg" => praxis_int_neg as *const (),
        "praxis_int_eq" => praxis_int_eq as *const (),
        "praxis_int_ne" => praxis_int_ne as *const (),
        "praxis_int_lt" => praxis_int_lt as *const (),
        "praxis_int_gt" => praxis_int_gt as *const (),
        "praxis_int_le" => praxis_int_le as *const (),
        "praxis_int_ge" => praxis_int_ge as *const (),
        "praxis_check_fault" => praxis_check_fault as *const (),
        "praxis_push_shadow_frame" => praxis_push_shadow_frame as *const (),
        "praxis_pop_shadow_frame" => praxis_pop_shadow_frame as *const (),
        "praxis_vec_new" => praxis_vec_new as *const (),
        "praxis_vec_push" => praxis_vec_push as *const (),
        "praxis_vec_len" => praxis_vec_len as *const (),
        "praxis_vec_get" => praxis_vec_get as *const (),
        "praxis_vec_is_empty" => praxis_vec_is_empty as *const (),
        "praxis_deque_new" => praxis_deque_new as *const (),
        "praxis_deque_push_front" => praxis_deque_push_front as *const (),
        "praxis_deque_push_back" => praxis_deque_push_back as *const (),
        "praxis_deque_pop_front" => praxis_deque_pop_front as *const (),
        "praxis_deque_pop_back" => praxis_deque_pop_back as *const (),
        "praxis_deque_len" => praxis_deque_len as *const (),
        "praxis_deque_get" => praxis_deque_get as *const (),
        "praxis_deque_is_empty" => praxis_deque_is_empty as *const (),
        "praxis_map_new" => praxis_map_new as *const (),
        "praxis_map_insert" => praxis_map_insert as *const (),
        "praxis_map_get" => praxis_map_get as *const (),
        "praxis_map_contains" => praxis_map_contains as *const (),
        "praxis_map_remove" => praxis_map_remove as *const (),
        "praxis_map_len" => praxis_map_len as *const (),
        "praxis_map_is_empty" => praxis_map_is_empty as *const (),
        "praxis_map_update_min" => praxis_map_update_min as *const (),
        "praxis_map_update_max" => praxis_map_update_max as *const (),
        "praxis_set_new" => praxis_set_new as *const (),
        "praxis_set_insert" => praxis_set_insert as *const (),
        "praxis_set_remove" => praxis_set_remove as *const (),
        "praxis_set_contains" => praxis_set_contains as *const (),
        "praxis_set_len" => praxis_set_len as *const (),
        "praxis_set_is_empty" => praxis_set_is_empty as *const (),
        "praxis_counter_new" => praxis_counter_new as *const (),
        "praxis_counter_get" => praxis_counter_get as *const (),
        "praxis_counter_inc" => praxis_counter_inc as *const (),
        "praxis_counter_len" => praxis_counter_len as *const (),
        "praxis_counter_is_empty" => praxis_counter_is_empty as *const (),
        "praxis_max_heap_new" => praxis_max_heap_new as *const (),
        "praxis_max_heap_push" => praxis_max_heap_push as *const (),
        "praxis_max_heap_pop" => praxis_max_heap_pop as *const (),
        "praxis_max_heap_peek" => praxis_max_heap_peek as *const (),
        "praxis_max_heap_len" => praxis_max_heap_len as *const (),
        "praxis_max_heap_is_empty" => praxis_max_heap_is_empty as *const (),
        "praxis_min_heap_new" => praxis_min_heap_new as *const (),
        "praxis_min_heap_push" => praxis_min_heap_push as *const (),
        "praxis_min_heap_pop" => praxis_min_heap_pop as *const (),
        "praxis_min_heap_peek" => praxis_min_heap_peek as *const (),
        "praxis_min_heap_len" => praxis_min_heap_len as *const (),
        "praxis_min_heap_is_empty" => praxis_min_heap_is_empty as *const (),
        "praxis_text_len" => praxis_text_len as *const (),
        "praxis_text_is_empty" => praxis_text_is_empty as *const (),
        "praxis_text_get" => praxis_text_get as *const (),
        "praxis_write_stdout" => praxis_write_stdout as *const (),
        "praxis_get_input" => praxis_get_input as *const (),
        "praxis_run_parser" => praxis_run_parser as *const (),
        "praxis_alloc_record" => praxis_alloc_record as *const (),
        "praxis_record_set_field" => praxis_record_set_field as *const (),
        "praxis_record_field" => praxis_record_field as *const (),
        "praxis_alloc_enum" => praxis_alloc_enum as *const (),
        "praxis_enum_set_payload" => praxis_enum_set_payload as *const (),
        "praxis_enum_tag" => praxis_enum_tag as *const (),
        "praxis_enum_payload" => praxis_enum_payload as *const (),
        "praxis_alloc_tuple" => praxis_alloc_tuple as *const (),
        "praxis_tuple_set" => praxis_tuple_set as *const (),
        "praxis_tuple_get" => praxis_tuple_get as *const (),
        "praxis_struct_eq" => praxis_struct_eq as *const (),
        "praxis_alloc_closure" => praxis_alloc_closure as *const (),
        "praxis_closure_set_capture" => praxis_closure_set_capture as *const (),
        "praxis_closure_fn_ptr" => praxis_closure_fn_ptr as *const (),
        "praxis_closure_capture" => praxis_closure_capture as *const (),
        "praxis_alloc_var_cell" => praxis_alloc_var_cell as *const (),
        "praxis_var_cell_get" => praxis_var_cell_get as *const (),
        "praxis_var_cell_set" => praxis_var_cell_set as *const (),
        "praxis_push_debug_frame" => praxis_runtime::debug::praxis_push_debug_frame as *const (),
        "praxis_pop_debug_frame" => praxis_runtime::debug::praxis_pop_debug_frame as *const (),
        _ => return None,
    };
    Some(ptr as *const u8)
}
